- include: server.yml

- name: Check replication on slave
  mysql_replication:
    mode: getslave
    login_user: "{{ root_user.name }}"
    login_password: "{{ root_user.password }}"
    login_port: "{{ mysql_port }}"
  register: replica_status
  ignore_errors: yes

# https://github.com/ansible/ansible-modules-core/issues/932
- name: Unpack sql dump
  shell: gunzip < "{{ backup_src }}" > /tmp/dump.sql
  when: 
    - replica_status.msg.find('Server is not configured as mysql slave') != -1   # TODO: error when replica is configured

- name: Seed database with dump
  mysql_db:
    name: all
    state: import
    target: /tmp/master_dump.sql
    login_user: "{{ root_user.name }}"
    login_password: "{{ root_user.password }}"
    login_port: "{{ mysql_port }}"
  when:
    - replica_status.msg.find('Server is not configured as mysql slave') != -1

- name: Removing temporary dump
  file:
    path: /tmp/master_dump.sql
    state: absent

- name: Set replication master
  mysql_replication:
    mode: changemaster
    master_host: "{{ hostvars[item].ansible_host }}"
    master_port: "{{ mysql_port }}"
    master_user: "{{ replication_user.name }}"
    master_password: "{{ replication_user.password }}"
    master_auto_position: 1
    login_user: "{{ root_user.name }}"
    login_password: "{{ root_user.password }}"
    login_port: "{{ mysql_port }}"
  when:
    - replica_status.msg.find('Server is not configured as mysql slave') != -1
    - "{{ hostvars[item].mysql_role == 'master' }}"
  with_items:
    - "{{ groups['mysql'] }}"

- name: Start replication
  mysql_replication:
    mode: startslave
    login_user: "{{ root_user.name }}"
    login_password: "{{ root_user.password }}"
    login_port: "{{ mysql_port }}"
  when:
    - replica_status.msg.find('Server is not configured as mysql slave') != -1

- name: Check replication status
  mysql_replication:
    mode: getslave
    login_user: "{{ root_user.name }}"
    login_password: "{{ root_user.password }}"
    login_port: "{{ mysql_port }}"
