- name: restart haproxy
  service: name=haproxy state=restarted enabled=yes

- name: restart mysqlchk
  service: name=mysqlchk.socket state=restarted enabled=yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['mysql'] }}"